#!/usr/bin/env bash
set -e

# session name
SESSION="$(basename "$PWD")"
SESSION="${SESSION//[^a-zA-Z0-9_.-]/_}"

# already in tmux → switch session
if [[ -n "${TMUX:-}" ]]; then
  exec tmux switch-client -t "$SESSION" \
    2>/dev/null || exec tmux new-session -A -s "$SESSION"
fi

# not in tmux → attach / new
exec tmux new-session -A -s "$SESSION"